/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BLS {
  export type PointG2Struct = {
    x: [BigNumberish, BigNumberish];
    y: [BigNumberish, BigNumberish];
  };

  export type PointG2StructOutput = [
    x: [bigint, bigint],
    y: [bigint, bigint]
  ] & { x: [bigint, bigint]; y: [bigint, bigint] };
}

export declare namespace TypesLib {
  export type CiphertextStruct = {
    u: BLS.PointG2Struct;
    v: BytesLike;
    w: BytesLike;
  };

  export type CiphertextStructOutput = [
    u: BLS.PointG2StructOutput,
    v: string,
    w: string
  ] & { u: BLS.PointG2StructOutput; v: string; w: string };
}

export declare namespace CryptoCatcherBlocklock {
  export type SealedSessionStruct = {
    player: AddressLike;
    sessionId: BigNumberish;
    requestId: BigNumberish;
    encryptedMultiplier: TypesLib.CiphertextStruct;
    condition: BytesLike;
    createdAt: BigNumberish;
    unlockTime: BigNumberish;
    isRevealed: boolean;
    revealedMultiplier: BigNumberish;
    sealType: BigNumberish;
  };

  export type SealedSessionStructOutput = [
    player: string,
    sessionId: bigint,
    requestId: bigint,
    encryptedMultiplier: TypesLib.CiphertextStructOutput,
    condition: string,
    createdAt: bigint,
    unlockTime: bigint,
    isRevealed: boolean,
    revealedMultiplier: bigint,
    sealType: bigint
  ] & {
    player: string;
    sessionId: bigint;
    requestId: bigint;
    encryptedMultiplier: TypesLib.CiphertextStructOutput;
    condition: string;
    createdAt: bigint;
    unlockTime: bigint;
    isRevealed: boolean;
    revealedMultiplier: bigint;
    sealType: bigint;
  };
}

export interface CryptoCatcherBlocklockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_decryptMultiplier"
      | "acceptOwnership"
      | "blocklock"
      | "createBlockSealedSession"
      | "createSubscriptionAndFundNative"
      | "createTimeSealedSession"
      | "emergencyReveal"
      | "fundContractNative"
      | "generateMultiplier"
      | "getBalance"
      | "getPlayerSealedSessions"
      | "getSealedSession"
      | "getSealedSessionByGameId"
      | "isInFlight"
      | "isReadyToReveal"
      | "nextSealId"
      | "owner"
      | "pendingRequestExists"
      | "playerSealedSessions"
      | "receiveBlocklock"
      | "sealedSessions"
      | "sessionIdToSealId"
      | "setBlocklock"
      | "setSubId"
      | "subscriptionId"
      | "topUpSubscriptionNative"
      | "transferOwnership"
      | "updateSubscription"
      | "withdrawNative"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Funded"
      | "MultiplierRevealed"
      | "NewSubscriptionId"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "Received"
      | "SealFailed"
      | "SealedSessionCreated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_decryptMultiplier",
    values: [TypesLib.CiphertextStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "blocklock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createBlockSealedSession",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscriptionAndFundNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTimeSealedSession",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyReveal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundContractNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateMultiplier",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerSealedSessions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSealedSession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSealedSessionByGameId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isInFlight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReadyToReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSealId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerSealedSessions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveBlocklock",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sealedSessions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionIdToSealId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlocklock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "topUpSubscriptionNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubscription",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_decryptMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blocklock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBlockSealedSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscriptionAndFundNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTimeSealedSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundContractNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerSealedSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSealedSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSealedSessionByGameId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isInFlight", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isReadyToReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextSealId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerSealedSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveBlocklock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sealedSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionIdToSealId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlocklock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSubId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpSubscriptionNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
}

export namespace FundedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiplierRevealedEvent {
  export type InputTuple = [
    sealId: BigNumberish,
    player: AddressLike,
    sessionId: BigNumberish,
    multiplier: BigNumberish
  ];
  export type OutputTuple = [
    sealId: bigint,
    player: string,
    sessionId: bigint,
    multiplier: bigint
  ];
  export interface OutputObject {
    sealId: bigint;
    player: string;
    sessionId: bigint;
    multiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewSubscriptionIdEvent {
  export type InputTuple = [subscriptionId: BigNumberish];
  export type OutputTuple = [subscriptionId: bigint];
  export interface OutputObject {
    subscriptionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedEvent {
  export type InputTuple = [arg0: AddressLike, arg1: BigNumberish];
  export type OutputTuple = [arg0: string, arg1: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SealFailedEvent {
  export type InputTuple = [sealId: BigNumberish, reason: string];
  export type OutputTuple = [sealId: bigint, reason: string];
  export interface OutputObject {
    sealId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SealedSessionCreatedEvent {
  export type InputTuple = [
    sealId: BigNumberish,
    player: AddressLike,
    sessionId: BigNumberish,
    sealType: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    sealId: bigint,
    player: string,
    sessionId: bigint,
    sealType: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    sealId: bigint;
    player: string;
    sessionId: bigint;
    sealType: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CryptoCatcherBlocklock extends BaseContract {
  connect(runner?: ContractRunner | null): CryptoCatcherBlocklock;
  waitForDeployment(): Promise<this>;

  interface: CryptoCatcherBlocklockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _decryptMultiplier: TypedContractMethod<
    [ciphertext: TypesLib.CiphertextStruct, decryptionKey: BytesLike],
    [bigint],
    "view"
  >;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  blocklock: TypedContractMethod<[], [string], "view">;

  createBlockSealedSession: TypedContractMethod<
    [
      sessionId: BigNumberish,
      unlockBlock: BigNumberish,
      encryptedMultiplier: BigNumberish,
      callbackGasLimit: BigNumberish
    ],
    [[bigint, bigint] & { sealId: bigint; requestPrice: bigint }],
    "payable"
  >;

  createSubscriptionAndFundNative: TypedContractMethod<[], [void], "payable">;

  createTimeSealedSession: TypedContractMethod<
    [
      sessionId: BigNumberish,
      unlockDelayMinutes: BigNumberish,
      encryptedMultiplier: BigNumberish,
      callbackGasLimit: BigNumberish
    ],
    [[bigint, bigint] & { sealId: bigint; requestPrice: bigint }],
    "payable"
  >;

  emergencyReveal: TypedContractMethod<
    [sealId: BigNumberish, multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundContractNative: TypedContractMethod<[], [void], "payable">;

  generateMultiplier: TypedContractMethod<
    [player: AddressLike, sessionType: BigNumberish, randomSeed: BytesLike],
    [bigint],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPlayerSealedSessions: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  getSealedSession: TypedContractMethod<
    [sealId: BigNumberish],
    [CryptoCatcherBlocklock.SealedSessionStructOutput],
    "view"
  >;

  getSealedSessionByGameId: TypedContractMethod<
    [sessionId: BigNumberish],
    [CryptoCatcherBlocklock.SealedSessionStructOutput],
    "view"
  >;

  isInFlight: TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;

  isReadyToReveal: TypedContractMethod<
    [sealId: BigNumberish],
    [boolean],
    "view"
  >;

  nextSealId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingRequestExists: TypedContractMethod<
    [subId: BigNumberish],
    [boolean],
    "view"
  >;

  playerSealedSessions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  receiveBlocklock: TypedContractMethod<
    [requestId: BigNumberish, decryptionKey: BytesLike],
    [void],
    "nonpayable"
  >;

  sealedSessions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        TypesLib.CiphertextStructOutput,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        player: string;
        sessionId: bigint;
        requestId: bigint;
        encryptedMultiplier: TypesLib.CiphertextStructOutput;
        condition: string;
        createdAt: bigint;
        unlockTime: bigint;
        isRevealed: boolean;
        revealedMultiplier: bigint;
        sealType: bigint;
      }
    ],
    "view"
  >;

  sessionIdToSealId: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  setBlocklock: TypedContractMethod<
    [_blocklock: AddressLike],
    [void],
    "nonpayable"
  >;

  setSubId: TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;

  subscriptionId: TypedContractMethod<[], [bigint], "view">;

  topUpSubscriptionNative: TypedContractMethod<[], [void], "payable">;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSubscription: TypedContractMethod<
    [consumers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_decryptMultiplier"
  ): TypedContractMethod<
    [ciphertext: TypesLib.CiphertextStruct, decryptionKey: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blocklock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createBlockSealedSession"
  ): TypedContractMethod<
    [
      sessionId: BigNumberish,
      unlockBlock: BigNumberish,
      encryptedMultiplier: BigNumberish,
      callbackGasLimit: BigNumberish
    ],
    [[bigint, bigint] & { sealId: bigint; requestPrice: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createSubscriptionAndFundNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "createTimeSealedSession"
  ): TypedContractMethod<
    [
      sessionId: BigNumberish,
      unlockDelayMinutes: BigNumberish,
      encryptedMultiplier: BigNumberish,
      callbackGasLimit: BigNumberish
    ],
    [[bigint, bigint] & { sealId: bigint; requestPrice: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "emergencyReveal"
  ): TypedContractMethod<
    [sealId: BigNumberish, multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundContractNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "generateMultiplier"
  ): TypedContractMethod<
    [player: AddressLike, sessionType: BigNumberish, randomSeed: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerSealedSessions"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSealedSession"
  ): TypedContractMethod<
    [sealId: BigNumberish],
    [CryptoCatcherBlocklock.SealedSessionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSealedSessionByGameId"
  ): TypedContractMethod<
    [sessionId: BigNumberish],
    [CryptoCatcherBlocklock.SealedSessionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInFlight"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isReadyToReveal"
  ): TypedContractMethod<[sealId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSealId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRequestExists"
  ): TypedContractMethod<[subId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "playerSealedSessions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveBlocklock"
  ): TypedContractMethod<
    [requestId: BigNumberish, decryptionKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sealedSessions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        TypesLib.CiphertextStructOutput,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        player: string;
        sessionId: bigint;
        requestId: bigint;
        encryptedMultiplier: TypesLib.CiphertextStructOutput;
        condition: string;
        createdAt: bigint;
        unlockTime: bigint;
        isRevealed: boolean;
        revealedMultiplier: bigint;
        sealType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sessionIdToSealId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBlocklock"
  ): TypedContractMethod<[_blocklock: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubId"
  ): TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "topUpSubscriptionNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSubscription"
  ): TypedContractMethod<[consumers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "MultiplierRevealed"
  ): TypedContractEvent<
    MultiplierRevealedEvent.InputTuple,
    MultiplierRevealedEvent.OutputTuple,
    MultiplierRevealedEvent.OutputObject
  >;
  getEvent(
    key: "NewSubscriptionId"
  ): TypedContractEvent<
    NewSubscriptionIdEvent.InputTuple,
    NewSubscriptionIdEvent.OutputTuple,
    NewSubscriptionIdEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Received"
  ): TypedContractEvent<
    ReceivedEvent.InputTuple,
    ReceivedEvent.OutputTuple,
    ReceivedEvent.OutputObject
  >;
  getEvent(
    key: "SealFailed"
  ): TypedContractEvent<
    SealFailedEvent.InputTuple,
    SealFailedEvent.OutputTuple,
    SealFailedEvent.OutputObject
  >;
  getEvent(
    key: "SealedSessionCreated"
  ): TypedContractEvent<
    SealedSessionCreatedEvent.InputTuple,
    SealedSessionCreatedEvent.OutputTuple,
    SealedSessionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Funded(address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "MultiplierRevealed(uint256,address,uint256,uint256)": TypedContractEvent<
      MultiplierRevealedEvent.InputTuple,
      MultiplierRevealedEvent.OutputTuple,
      MultiplierRevealedEvent.OutputObject
    >;
    MultiplierRevealed: TypedContractEvent<
      MultiplierRevealedEvent.InputTuple,
      MultiplierRevealedEvent.OutputTuple,
      MultiplierRevealedEvent.OutputObject
    >;

    "NewSubscriptionId(uint256)": TypedContractEvent<
      NewSubscriptionIdEvent.InputTuple,
      NewSubscriptionIdEvent.OutputTuple,
      NewSubscriptionIdEvent.OutputObject
    >;
    NewSubscriptionId: TypedContractEvent<
      NewSubscriptionIdEvent.InputTuple,
      NewSubscriptionIdEvent.OutputTuple,
      NewSubscriptionIdEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Received(address,uint256)": TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;
    Received: TypedContractEvent<
      ReceivedEvent.InputTuple,
      ReceivedEvent.OutputTuple,
      ReceivedEvent.OutputObject
    >;

    "SealFailed(uint256,string)": TypedContractEvent<
      SealFailedEvent.InputTuple,
      SealFailedEvent.OutputTuple,
      SealFailedEvent.OutputObject
    >;
    SealFailed: TypedContractEvent<
      SealFailedEvent.InputTuple,
      SealFailedEvent.OutputTuple,
      SealFailedEvent.OutputObject
    >;

    "SealedSessionCreated(uint256,address,uint256,uint8,uint256)": TypedContractEvent<
      SealedSessionCreatedEvent.InputTuple,
      SealedSessionCreatedEvent.OutputTuple,
      SealedSessionCreatedEvent.OutputObject
    >;
    SealedSessionCreated: TypedContractEvent<
      SealedSessionCreatedEvent.InputTuple,
      SealedSessionCreatedEvent.OutputTuple,
      SealedSessionCreatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
