/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomNumberGeneratorSol from "./RandomNumberGenerator.sol";
export type { randomNumberGeneratorSol };
export type { CryptoCatcherBlocklock } from "./CryptoCatcherBlocklock";
export type { CryptoCatcherRandomness } from "./CryptoCatcherRandomness";
export type { EnhancedGameClaims } from "./EnhancedGameClaims";
export type { GameClaims } from "./GameClaims";
export type { MockERC20 } from "./MockERC20";
export type { UserManager } from "./UserManager";
