/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlocklockReceiver,
  IBlocklockReceiverInterface,
} from "../../../../blocklock-solidity/src/interfaces/IBlocklockReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "decryptionKey",
        type: "bytes",
      },
    ],
    name: "receiveBlocklock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlocklockReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IBlocklockReceiverInterface {
    return new Interface(_abi) as IBlocklockReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBlocklockReceiver {
    return new Contract(address, _abi, runner) as unknown as IBlocklockReceiver;
  }
}
