/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomnessReceiver,
  IRandomnessReceiverInterface,
} from "../../../../randomness-solidity/src/interfaces/IRandomnessReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestID",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "randomness",
        type: "bytes32",
      },
    ],
    name: "receiveRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomnessReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomnessReceiverInterface {
    return new Interface(_abi) as IRandomnessReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomnessReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRandomnessReceiver;
  }
}
