/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  BLS,
  BLSInterface,
} from "../../../../randomness-solidity/src/libraries/BLS";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[4]",
        name: "input",
        type: "uint256[4]",
      },
    ],
    name: "BNAddFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "dst",
        type: "bytes",
      },
    ],
    name: "InvalidDSTLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "InvalidFieldElement",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "noSqrt",
        type: "uint256",
      },
    ],
    name: "MapToPointFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "base",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exponent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "modulus",
        type: "uint256",
      },
    ],
    name: "ModExpFailed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200af244732093588668c5c57356c6741b71d229140a24d2c7afda820e0ae0f51a64736f6c63430008140033";

type BLSConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BLSConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BLS__factory extends ContractFactory {
  constructor(...args: BLSConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BLS & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BLS__factory {
    return super.connect(runner) as BLS__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BLSInterface {
    return new Interface(_abi) as BLSInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BLS {
    return new Contract(address, _abi, runner) as unknown as BLS;
  }
}
