/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlocklockReceiver } from "./IBlocklockReceiver";
export type { IBlocklockSender } from "./IBlocklockSender";
export type { IOwnable } from "./IOwnable";
export type { ISubscription } from "./ISubscription";
