'use client';

import { Suspense } from 'react';
import EnhancedCryptoGame from '@/components/enhanced-crypto-game';
import LoadingSpinner from '@/components/loader-spinner';
import Link from 'next/link';
import { useAccount } from 'wagmi';
import { ConnectWallet } from '@/components/walletConnect';

export default function EnhancedGamePage() {
  const { isConnected } = useAccount();

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-4">🎮 Enhanced Crypto Catcher</h1>
          <div className="flex items-center gap-6 text-sm text-gray-600 dark:text-gray-400">
            <Link href="/" className="hover:text-blue-500">← Home</Link>
            <Link href="/crypto-catcher" className="hover:text-blue-500">Classic Mode</Link>
            <Link href="/crypto-catcher/claims" className="hover:text-blue-500">Claims</Link>
          </div>
        </div>

        {/* Feature Highlights */}
        <div className="mb-8 grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-purple-100 dark:bg-purple-900 rounded-lg p-4">
            <h3 className="font-bold text-lg mb-2">🎲 VRF Randomness</h3>
            <p className="text-sm">Unpredictable level changes powered by verifiable random functions</p>
          </div>
          <div className="bg-blue-100 dark:bg-blue-900 rounded-lg p-4">
            <h3 className="font-bold text-lg mb-2">🔐 Sealed Sessions</h3>
            <p className="text-sm">Hidden reward multipliers revealed after gameplay using blocklock encryption</p>
          </div>
          <div className="bg-green-100 dark:bg-green-900 rounded-lg p-4">
            <h3 className="font-bold text-lg mb-2">👥 User Profiles</h3>
            <p className="text-sm">Levels, achievements, and leaderboards with enhanced rewards</p>
          </div>
        </div>

        {/* Wallet Connection */}
        {!isConnected && (
          <div className="mb-8 bg-yellow-100 dark:bg-yellow-900 rounded-lg p-6 text-center">
            <h2 className="text-2xl font-bold mb-4">Connect Wallet to Play Enhanced Mode</h2>
            <p className="mb-6 text-gray-700 dark:text-gray-300">
              Enhanced Crypto Catcher requires wallet connection to access VRF randomness, 
              sealed sessions, and blockchain-based rewards.
            </p>
            <ConnectWallet />
          </div>
        )}

        {/* Game Interface */}
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 shadow-md">
          {isConnected ? (
            <>
              <div className="mb-6">
                <h2 className="text-2xl font-bold mb-2">🎯 VRF-Enhanced Gameplay</h2>
                <p className="text-gray-600 dark:text-gray-400">
                  Experience crypto catching with verifiable randomness! Level changes occur at 
                  unpredictable score thresholds generated by VRF, creating truly fair gameplay.
                </p>
              </div>
              
              <Suspense fallback={<LoadingSpinner />}>
                <EnhancedCryptoGame />
              </Suspense>
            </>
          ) : (
            <div className="text-center py-12">
              <h3 className="text-xl font-bold mb-4">Wallet Required</h3>
              <p className="text-gray-600 dark:text-gray-400 mb-6">
                Please connect your wallet above to access enhanced features.
              </p>
              <Link 
                href="/crypto-catcher"
                className="px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
              >
                Play Classic Mode (No Wallet Required)
              </Link>
            </div>
          )}
          
          {/* How to Play Enhanced */}
          <div className="mt-12 border-t dark:border-gray-700 pt-8">
            <h2 className="text-2xl font-bold mb-6">🎮 Enhanced Mode Features</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* VRF Features */}
              <div>
                <h3 className="text-lg font-bold mb-4">🎲 VRF Randomness</h3>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-green-500 font-bold">✓</span>
                    <div>
                      <strong>Random Level Changes:</strong> Game difficulty increases at unpredictable score thresholds
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-500 font-bold">✓</span>
                    <div>
                      <strong>Session Types:</strong> FREE, BRONZE, SILVER, GOLD, PLATINUM with different multipliers
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-500 font-bold">✓</span>
                    <div>
                      <strong>Provably Fair:</strong> All randomness is verifiable on-chain
                    </div>
                  </li>
                </ul>
              </div>

              {/* Blocklock Features */}
              <div>
                <h3 className="text-lg font-bold mb-4">🔐 Sealed Sessions</h3>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-blue-500 font-bold">✓</span>
                    <div>
                      <strong>Hidden Multipliers:</strong> Reward multipliers encrypted until reveal time
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-blue-500 font-bold">✓</span>
                    <div>
                      <strong>Time-locked Reveals:</strong> Multipliers unlock after specified time
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-blue-500 font-bold">✓</span>
                    <div>
                      <strong>Surprise Factor:</strong> Creates excitement and prevents gaming
                    </div>
                  </li>
                </ul>
              </div>

              {/* User System */}
              <div>
                <h3 className="text-lg font-bold mb-4">👥 User Progression</h3>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-purple-500 font-bold">✓</span>
                    <div>
                      <strong>User Profiles:</strong> Register username and track stats
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-purple-500 font-bold">✓</span>
                    <div>
                      <strong>Achievements:</strong> Unlock achievements for XP and level progression
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-purple-500 font-bold">✓</span>
                    <div>
                      <strong>Leaderboards:</strong> Compete on daily, weekly, and all-time boards
                    </div>
                  </li>
                </ul>
              </div>

              {/* Enhanced Rewards */}
              <div>
                <h3 className="text-lg font-bold mb-4">💰 Enhanced Rewards</h3>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-yellow-500 font-bold">✓</span>
                    <div>
                      <strong>Multi-layer Multipliers:</strong> Session + Seal + Level bonuses stack
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-yellow-500 font-bold">✓</span>
                    <div>
                      <strong>Level Bonuses:</strong> Higher user levels earn more rewards
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-yellow-500 font-bold">✓</span>
                    <div>
                      <strong>USDC Payouts:</strong> Earn real USDC rewards on Base network
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Technical Info */}
          <div className="mt-8 p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
            <h3 className="font-bold mb-2">🔧 Technical Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
              <div>
                <strong>Network:</strong> Base Sepolia (Testnet)<br/>
                <strong>VRF Provider:</strong> Randamu Network<br/>
                <strong>Encryption:</strong> dcipher Blocklock
              </div>
              <div>
                <strong>Gas Optimization:</strong> Batched operations<br/>
                <strong>Security:</strong> Multi-signature validation<br/>
                <strong>Upgradeability:</strong> Proxy-based contracts
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
